### PR TITLE
python 3.6 migration 

### LINKED ISSUE #79: Migrate RCS to use Python v3
Update rcs to use Python `v3.6.4`.  The main impetus for the upgrade is to gain access to enhanced https/ssl support.  It's also generally good to upgrade to a more modern version (`v3.0.0` came out in late 2008; `v2.0.1` was in 2001).

The python source code in rcs *should* be compatible with `v3.x`. 

Primary tasks

* installing / updating python on `rcs` hosting server
* investigating dependencies in `requirements.txt` and `requirements-dev.txt`, updating versions if appropriate.
* a real thorough amount of testing
* updating docs
  * `readme.rst`
  * `docs/conf.py`
  * `docs/dev/setup.rst`
  * `docs/admin/deployment.rst`
* argue about new rcs version number and update it

### PR DESCRIPTION
**Pull request by barryytm**
Closes #79 

Link to test: http://section917.cloudapp.net:8080/static/test.html

JSON  sample snippet for testing:
```
{  
   "version":"2.0",
   "fr":{  
      "service_url":"https://agrimaps.gov.mb.ca/arcgis/rest/services/AGRIMAPS/AGRIMAPS/MapServer/3",
      "service_type":"esriFeature",
      "service_name":"Trunk Highways du Provincial"
   },
   "en":{  
      "service_url":"https://agrimaps.gov.mb.ca/arcgis/rest/services/AGRIMAPS/AGRIMAPS/MapServer/3",
      "service_type":"esriFeature",
      "service_name":"Provincial Trunk Highways"
   }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/85)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[requirements.txt, line 4 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/85#-L8DR-v4siEvfA7HPmPa:-L8DR-v4siEvfA7HPmPb:b-arv3wy) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/requirements.txt#L4)):*
> ```
> Flask-RESTful==0.3.6
> jsonschema==2.6.0
> requests==2.2.1
> ```

why did requests move to such an old version?

---

*[Vagrantfile, line 47 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/85#-L8DRMuMOXs3kDJcNRCo:-L8DRMuMOXs3kDJcNRCp:bn0spmy) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/Vagrantfile#L47)):*
> ```Ruby
> 
>   config.vm.provision "shell", inline: <<-SHELL
>     sudo add-apt-repository ppa:deadsnakes/ppa
> ```

instead of using a ppa it would be better to update the base OS version, ubuntu 14.04 is only a year away from dropping support

when looking for new vagrant images it's probably better to look for an image which is supported by vagrant

---

*[Vagrantfile, line 56 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/85#-L8DS53Y_KU-RURgZeNG:-L8DS53Y_KU-RURgZeNH:b-kpe790) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/Vagrantfile#L56)):*
> ```Ruby
>     curl -X PUT http://127.0.0.1:5984/rcs_auth
>     cd /vagrant
>     virtualenv --always-copy -p python3.6 .
> ```

please use the new venv module with python 3 (this should also remove the need for python-virtualenv as a package)

---

*[services/upgrade.py, line 53 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/85#-L8DShtU65CR4athNO2a:-L8DShtU65CR4athNO2b:b-flk6z0) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/services/upgrade.py#L53)):*
> ```Python
>             upgrade_method = wms_upgrade if v1_request['payload_type'] == 'wms' else feat_upgrade
>             v2_request = {lang: upgrade_method(v1_request[lang]) for lang in current_app.config['LANGS']}
>             print(v2_request)
> ```

this should probably get converted to a log if we want to keep it, and if not delete it

---

*[services/regparse/universal.py, line 56 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/85#-L8DT1E43axklKlA3hR9:-L8DT1E89o3XWAmd6KVg:b929t9t) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/services/regparse/universal.py#L56)):*
> ```Python
>             endpoint += '?VERSION=1.1.1&REQUEST=GetCapabilities&SERVICE=wms'
>         r = requests.get(endpoint)
>         print(r.status_code)
> ```

print statements should become logs or be removed, these are probably left over from debugging sessions

---

*[test/__init__.py, line 0 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/85#-L8DTUgMQ7p_7ip9JL-w:-L8DTUgMQ7p_7ip9JL-x:bllgpi7) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/test/__init__.py#L0)):*
why is test becoming a package?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/85)*

**Comment by james-rae** [comment]
Reviewed 22 of 27 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[setup.py, line 10 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/85#-L8YjvJtEOhtzaEB8FqV:-L8YjvJuq3w4qp1C0ajr:bsioxf9) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/a8b6e04a33c54a4df4b4e79d372a8d160e39beca/setup.py#L10)):*
> ```Python
>     name="rcs",
>     description="RAMP Configuration Service",
>     version="2.4.0",
> ```

would a change this large be a `v3.0.0`?  @alyec ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/85)*

**Comment by alyec** [comment]
Reviewed 6 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[setup.py, line 10 at r2](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8YjvJtEOhtzaEB8FqV:-L8h-WMKAcqRFKrMM7Ql:b-h9sacz) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/a8b6e04a33c54a4df4b4e79d372a8d160e39beca/setup.py#L10)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

would a change this large be a `v3.0.0`?  @alyec ?
</blockquote></details>

when we add a "from __future__ import ..." that generally means the app can work in python2 as well as python3
https://github.com/fgpv-vpgf/rcs/blob/develop/run.py#L5

the sigcheck module may break and need custom code to run in 2 as it is now

given the scope of the changes I'd be willing to go with a 2.4 or a 3.0 as I'm not entirely clear on where something like this stands

if we're dropping support for all python2 installs I'd say go with 3.0

---

*[Vagrantfile, line 51 at r2](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8gztzJEvWzQZ5Ugh0w:-L8gztzJEvWzQZ5Ugh0x:b-4lnbec) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/a8b6e04a33c54a4df4b4e79d372a8d160e39beca/Vagrantfile#L51)):*
> ```Ruby
>     netstat -antp
>     sleep 5
>     curl -X DELETE http://localhost:5984/rcs_cache
> ```

why are these deletes needed?

---

*[Vagrantfile, line 57 at r2](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8h-4d5Dk9EesYLX_K-:-L8h-4d5Dk9EesYLX_K0:b-9u6pb) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/a8b6e04a33c54a4df4b4e79d372a8d160e39beca/Vagrantfile#L57)):*
> ```Ruby
>     cd /vagrant
>     python3.6 -m venv rcs-venv
>     . rcs-venv/bin/activate
> ```

what's the reason for moving the venv into a separate directory?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85)*

**Comment by barryytm** [comment]
Review status: 21 of 27 files reviewed at latest revision, 9 unresolved discussions.

---

*[setup.py, line 10 at r2](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8YjvJtEOhtzaEB8FqV:-L9HDDfFBZP-WhBg9m4b:bubcpy9) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/a8b6e04a33c54a4df4b4e79d372a8d160e39beca/setup.py#L10)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

when we add a "from __future__ import ..." that generally means the app can work in python2 as well as python3
https://github.com/fgpv-vpgf/rcs/blob/develop/run.py#L5

the sigcheck module may break and need custom code to run in 2 as it is now

given the scope of the changes I'd be willing to go with a 2.4 or a 3.0 as I'm not entirely clear on where something like this stands

if we're dropping support for all python2 installs I'd say go with 3.0
</blockquote></details>

Changed to 3.0

---

*[Vagrantfile, line 47 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8DRMuMOXs3kDJcNRCo:-L9HDI0u0iehkf7axHS0:bmvsba0) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/Vagrantfile#L47)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

instead of using a ppa it would be better to update the base OS version, ubuntu 14.04 is only a year away from dropping support

when looking for new vagrant images it's probably better to look for an image which is supported by vagrant
</blockquote></details>

Changed to 16.04, thanks.

---

*[Vagrantfile, line 56 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8DS53Y_KU-RURgZeNG:-L9HDUwX58DjugglM4de:b-dtkdrq) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/Vagrantfile#L56)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

please use the new venv module with python 3 (this should also remove the need for python-virtualenv as a package)
</blockquote></details>

Done, thanks.

---

*[Vagrantfile, line 51 at r2](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8gztzJEvWzQZ5Ugh0w:-L9HDR1oDQpPf8OuH1kD:b-njzfze) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/a8b6e04a33c54a4df4b4e79d372a8d160e39beca/Vagrantfile#L51)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

why are these deletes needed?
</blockquote></details>

Removed, thanks.

---

*[Vagrantfile, line 57 at r2](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8h-4d5Dk9EesYLX_K-:-L9HDWcg9NwIpHgo2Lxe:bt89vwx) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/a8b6e04a33c54a4df4b4e79d372a8d160e39beca/Vagrantfile#L57)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

what's the reason for moving the venv into a separate directory?
</blockquote></details>

Moved back to the same directory, thanks.

---

*[services/upgrade.py, line 53 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8DShtU65CR4athNO2a:-L9HDeumC5cR4OU3xg0U:b-njzfze) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/services/upgrade.py#L53)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

this should probably get converted to a log if we want to keep it, and if not delete it
</blockquote></details>

Removed, thanks.

---

*[services/regparse/universal.py, line 56 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8DT1E43axklKlA3hR9:-L9HDk_CEz4SQuEkdENZ:b-jwe7po) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/services/regparse/universal.py#L56)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

print statements should become logs or be removed, these are probably left over from debugging sessions
</blockquote></details>

Removed, thanks.

---

*[requirements.txt, line 4 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8DR-v4siEvfA7HPmPa:-L9HDyE4B-D6Fa6ZrXcb:b-gck4lu) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/requirements.txt#L4)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

why did requests move to such an old version?
</blockquote></details>

Thought it was newer.  Reverted back, thanks.

---

*[test/__init__.py, line  at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8DTUgMQ7p_7ip9JL-w:-L9HEE3a9L18VM2khghR:b-njzfze) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/test/__init__.py#L)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

why is test becoming a package?
</blockquote></details>

Removed, thanks.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85)*

**Comment by alyec** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Vagrantfile, line 47 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8DRMuMOXs3kDJcNRCo:-L9HFFTb27t_iTik0TPw:b-1a4zfq) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/Vagrantfile#L47)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

Changed to 16.04, thanks.
</blockquote></details>

please check `bento/ubuntu-16.04` as if that's usable then we're better off going with that image

also, which version of couchdb is being installed?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85)*

**Comment by barryytm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Vagrantfile, line 47 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8DRMuMOXs3kDJcNRCo:-L9MM2Y77Vk2qSTXMzQF:b95wy5z) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/Vagrantfile#L47)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

please check `bento/ubuntu-16.04` as if that's usable then we're better off going with that image

also, which version of couchdb is being installed?
</blockquote></details>

I wasn't able to install couchdb on `bento/ubuntu-16.04`.  The current installed version of couchdb is 1.6.0.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85)*

**Comment by james-rae** [comment]
Reviewed 6 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/rcs/85)*

**Comment by barryytm** [comment]
Reviewed 19 of 27 files at r1, 2 of 7 files at r2, 6 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Vagrantfile, line 47 at r1](https://reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8DRMuMOXs3kDJcNRCo:-LBfMAFh1r6jiW8UrwXy:b-153m43) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/Vagrantfile#L47)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary><blockquote>

Can you try the 2.x line installation source from the apache repos at http://docs.couchdb.org/en/2.1.1/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages ?  Try this on `bento/ubuntu-16.04` and see how it goes.
</blockquote></details>

CouchDB 2.x requires a configuration file.  Will keep it at 1.6.0 for now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/85)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Vagrantfile, line 47 at r1](https://reviewable.io/reviews/fgpv-vpgf/rcs/85#-L8DRMuMOXs3kDJcNRCo:-LBfNDaH-lw5AmoSqYNB:b-leuib7) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5d4bbaf44831e670f3f9cbd5dba606a8da4ee316/Vagrantfile#L47)):*
<details><summary><i>Previously, barryytm (Barry Yung) wrote…</i></summary><blockquote>

CouchDB 2.x requires a configuration file.  Will keep it at 1.6.0 for now.
</blockquote></details>

To clarify, it's not due to the config file but rather that it doesn't come with the xenial image, and no one wants to spend enough time to install from source.  We may also end up changing from vagrant to docker for the development platform.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/85)*

**Pull request merged**
