### PR TITLE
HTTP_PROXY support and all_keys debug endpoint

### PR DESCRIPTION
**Pull request by dan-bowerman**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/37)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 4 of 10 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Comment by james-rae** [comment]
Reviewed 4 of 10 files at r1, 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Comment by alyec** [comment]
Reviewed 3 of 10 files at r1, 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[config.py, line 27 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37#-KGwucBhUysyn0m2HR5S:-KGwucBhUysyn0m2HR5T:-554234552) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/fbfaf701a9d5a55ce53a0cfbd53dbed97fa011e6/config.py#L27)):*
I think we should leave this off in the default config.

---

*[run.py, line 66 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37#-KGwujpbNsrzSx1Qb9OC:-KGwujpc7rPbcD9yu0VM:-1308479603) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/fbfaf701a9d5a55ce53a0cfbd53dbed97fa011e6/run.py#L66)):*
To avoid `global` declarations attach this to `flask.g`: `flask.g.proxies = {'http': app.config['HTTP_PROXY'], 'https': app.config['HTTP_PROXY']}`

---

*[services/db/doc.py, line 117 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37#-KGwwApbxtJ296jGLrmz:-KGwwApc3s_ffNyaioP-:579675951) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/fbfaf701a9d5a55ce53a0cfbd53dbed97fa011e6/services/db/doc.py#L117)):*
If you return an array of objects `json.dumps` will take care of the conversion for you.  Try:
```python
try:
  return [ {'key':key} for key in _db.all(None, '_id', 'True')]
except pycouchdb.exceptions.NotFound:
  pass
return None
```

---

*[services/regparse/esri.py, line 7 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37#-KGwvmNg0UsX2vSc8F9r:-KGwvmNhY4nOy6JsQHKO:1800611789) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/fbfaf701a9d5a55ce53a0cfbd53dbed97fa011e6/services/regparse/esri.py#L7)):*
Following on the `flask.g` comment above, you should be able to import `flask` here and get access to the proxies variable that way.  Same with `universal.py`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Comment by spencerwahl** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Comment by alyec** [comment]
Reviewed 1 of 10 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[services/db/doc.py, line 122 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37#-KH0uF_arz_4mLi9jkC2:-KH0uF_arz_4mLi9jkC3:-84896891) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/e418c3a2a9ad46b4ecc28d2f342f67d92d191098/services/db/doc.py#L122)):*
You don't have to pull everything out of the list comprehension:
```python
[{'key': entry['_id'], 'url': entry['layer_config'][lang]['url']} for entry in _db.all(None, None, 'True') if 'layer_config' in entry]
```

I'm not sure what the behaviour should be in the case where the layer is not fully configured (ex: v1 style record which has not been upgraded).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Comment by james-rae** [comment]
Reviewed 4 of 5 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Comment by dan-bowerman** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[config.py, line 27 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37#-KGwucBhUysyn0m2HR5S:-KHLu5c3HvBU94SoJCPV:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/fbfaf701a9d5a55ce53a0cfbd53dbed97fa011e6/config.py#L27)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I think we should leave this off in the default config.</details>
Done.

---

*[run.py, line 66 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37#-KGwujpbNsrzSx1Qb9OC:-KHLu7hzH7Mr7wPwGbHm:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/fbfaf701a9d5a55ce53a0cfbd53dbed97fa011e6/run.py#L66)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> To avoid `global` declarations attach this to `flask.g`: `flask.g.proxies = {'http': app.config['HTTP_PROXY'], 'https': app.config['HTTP_PROXY']}`</details>
Done.

---

*[services/db/doc.py, line 117 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37#-KGwwApbxtJ296jGLrmz:-KHLu8TfWc1ZUZ4uyGWx:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/fbfaf701a9d5a55ce53a0cfbd53dbed97fa011e6/services/db/doc.py#L117)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> If you return an array of objects `json.dumps` will take care of the conversion for you.  Try:
> ```python
> try:
>   return [ {'key':key} for key in _db.all(None, '_id', 'True')]
> except pycouchdb.exceptions.NotFound:
>   pass
> return None
> ```</details>
Done.

---

*[services/db/doc.py, line 122 \[r4\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37#-KH0uF_arz_4mLi9jkC2:-KHLu9-jz_bhhiD6pSqy:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/e418c3a2a9ad46b4ecc28d2f342f67d92d191098/services/db/doc.py#L122)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> You don't have to pull everything out of the list comprehension:
> ```python
> [{'key': entry['_id'], 'url': entry['layer_config'][lang]['url']} for entry in _db.all(None, None, 'True') if 'layer_config' in entry]
> ```
> 
> I'm not sure what the behaviour should be in the case where the layer is not fully configured (ex: v1 style record which has not been upgraded).</details>
Done.

---

*[services/regparse/esri.py, line 7 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37#-KGwvmNg0UsX2vSc8F9r:-KHLuA5AMT3pnVFo9swa:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/fbfaf701a9d5a55ce53a0cfbd53dbed97fa011e6/services/regparse/esri.py#L7)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Following on the `flask.g` comment above, you should be able to import `flask` here and get access to the proxies variable that way.  Same with `universal.py`.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/37)*

**Pull request merged**
