### PR TITLE
feat(rcs): Added v2 Update endpoint

### LINKED ISSUE #9: Create new Update Endpoint
Replace existing simplification factor endpoint to a more general update feature.  Would allow for individual records to have specific attributes updated.

### PR DESCRIPTION
**Pull request by dan-bowerman**
RCS v2 now supports the ability to update specific fields in a previous registration, without re-registering wholesale.

Closes #9

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/58)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[services/update.py, line 28 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58#-KTLQdc_ikn9qCAegX8v:-KTLQdc_ikn9qCAegX8w:b-vxqlrp) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/733dcb324a54925bc3e02501164c6a8d578ffbfd/services/update.py#L28)):*
> ```Python
>                 return '{"msg":"Record not found in database"}', 404
>         except Exception as e:
>             msg = {'msg': 'Error: {0}'.format(e.message)}
> ```

This is probably not something the client has control over since it's a general exception (e.g. database is down).  `4xx` errors should be used if the client can change something to get a proper response but this should probably be a `500` error and maybe we don't want to pass the message along.

---

*[services/update.py, line 34 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58#-KTLU8VUScoSj82YORcf:-KTLU8VUScoSj82YORcg:b-5mdqrs) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/733dcb324a54925bc3e02501164c6a8d578ffbfd/services/update.py#L34)):*
> ```Python
>             payload = json.loads(request.data)
>             for x in langs:
>                 # The generic fields to update
> ```

Might be easier to add a small helper:
```python
request_seg = dbdata['request'][x]
payload_seg = payload[x]

def replace_if_set(params):
  for p in params:
    request_segment[p] = payload_seg[p]

replace_if_set('service_url service_name metadata'.split())
if payload_seg['service_type'] in ['esriFeature', 'esriImage', 'esriTile']:
  replace_if_set(['display_field'])
elif payload_seg['service_type'] == 'esriMapServer':
  replace_if_set(['scrape_only', 'recursive'])
elif payload_seg['service_type'] == 'ogcWms':
  replace_if_set(['scrape_only', 'recursive', 'legend_format', 'feature_info_format'])
```

---

*[services/update.py, line 64 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58#-KTLYWk0ox6vz3-NZaEy:-KTLYWk14bGFYXSxyPv3:b-2h4zka) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/733dcb324a54925bc3e02501164c6a8d578ffbfd/services/update.py#L64)):*
> ```Python
>             db.put_doc(key, payload[x]["service_type"], dbdata["request"], layer_config=v2_node, v1_config=v1_node)
>         except Exception as e:
>             msg = {'msg': 'Error: {0}'.format(e.message)}
> ```

Same issue as above with respect to the exception.  If there is a way we can identify genuine bad requests (`400`s as opposed to `500`s) we should try.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58)*

**Comment by james-rae** [comment]
Reviewed 4 of 5 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58)*

**Comment by alyec** [comment]
Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[services/regparse/ogc.py, line 72 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58#-KUSBWX1YFOF4BlkyMB_:-KUSBWX2J2V8v9vNyB3S:ba2mfg) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/05906891638cdaf635d028f7c554aad2c42a346d/services/regparse/ogc.py#L72)):*
> ```Python
>     :type str
>     """
>     xmldoc = minidom.parseString(query_service)
> ```

Since XML parsing is expensive it's probably better to scrape all the data upfront.

```python
def parseCapabilities(capabilties_xml_string):
  ret = {}
  xmldoc = minidom.parseString(capabilties_xml_string)
  for layer in xmldoc.getElementsByTagName('Layer'):
    id = layer..getElementsByTagName('Name')[0].firstChild.data
    title = layer.getElementsByTagName('Title')[0].firstChild.data
    queryable = str2bool(layer.getAttribute('queryable'))
    ret[id] = dict(title=title, queryable=queryable)
  return ret
``` 

in `make_wms_node` you could call this immediately after the capabilities call and use if for both `scrape_only` and `recursive`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58)*

**Comment by dan-bowerman** [comment]
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[services/update.py, line 28 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58#-KTLQdc_ikn9qCAegX8v:-KUSDjQZuOmn5XS9BVcv:b-896fix) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/733dcb324a54925bc3e02501164c6a8d578ffbfd/services/update.py#L28)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> This is probably not something the client has control over since it's a general exception (e.g. database is down).  `4xx` errors should be used if the client can change something to get a proper response but this should probably be a `500` error and maybe we don't want to pass the message along.
</details>
Done.

---

*[services/update.py, line 34 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58#-KTLU8VUScoSj82YORcf:-KUSW3hmqbWQsW60yXV9:b-896fix) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/733dcb324a54925bc3e02501164c6a8d578ffbfd/services/update.py#L34)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Might be easier to add a small helper:
> ```python
> request_seg = dbdata['request'][x]
> payload_seg = payload[x]
> 
> def replace_if_set(params):
>   for p in params:
>     request_segment[p] = payload_seg[p]
> 
> replace_if_set('service_url service_name metadata'.split())
> if payload_seg['service_type'] in ['esriFeature', 'esriImage', 'esriTile']:
>   replace_if_set(['display_field'])
> elif payload_seg['service_type'] == 'esriMapServer':
>   replace_if_set(['scrape_only', 'recursive'])
> elif payload_seg['service_type'] == 'ogcWms':
>   replace_if_set(['scrape_only', 'recursive', 'legend_format', 'feature_info_format'])
> ```
</details>
Done.

---

*[services/update.py, line 64 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58#-KTLYWk0ox6vz3-NZaEy:-KUSDoAqP4YW1i6ybmAn:b-896fix) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/733dcb324a54925bc3e02501164c6a8d578ffbfd/services/update.py#L64)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Same issue as above with respect to the exception.  If there is a way we can identify genuine bad requests (`400`s as opposed to `500`s) we should try.
</details>
Done.

---

*[services/regparse/ogc.py, line 72 at r3](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58#-KUSBWX1YFOF4BlkyMB_:-KUSVyIizJ3mx0gHhXN_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/05906891638cdaf635d028f7c554aad2c42a346d/services/regparse/ogc.py#L72)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Since XML parsing is expensive it's probably better to scrape all the data upfront.
> 
> ```python
> def parseCapabilities(capabilties_xml_string):
>   ret = {}
>   xmldoc = minidom.parseString(capabilties_xml_string)
>   for layer in xmldoc.getElementsByTagName('Layer'):
>     id = layer..getElementsByTagName('Name')[0].firstChild.data
>     title = layer.getElementsByTagName('Title')[0].firstChild.data
>     queryable = str2bool(layer.getAttribute('queryable'))
>     ret[id] = dict(title=title, queryable=queryable)
>   return ret
> ``` 
> 
> in `make_wms_node` you could call this immediately after the capabilities call and use if for both `scrape_only` and `recursive`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[services/update.py, line 34 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58#-KTLU8VUScoSj82YORcf:-KUT11qctxY3XE0XVNQW:br8sy11) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/733dcb324a54925bc3e02501164c6a8d578ffbfd/services/update.py#L34)):*
<details><summary><i>Previously, dan-bowerman (Dan Bowerman) wrote…</i></summary>
> Done.
</details>
I don't see this change, did you forget a commit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58)*

**Comment by dan-bowerman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[services/update.py, line 34 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58#-KTLU8VUScoSj82YORcf:-KUT5FNwwxHAEDuwBJbj:bulztft) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/733dcb324a54925bc3e02501164c6a8d578ffbfd/services/update.py#L34)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I don't see this change, did you forget a commit?
</details>
I will roll this into another issue and take care of it later. I need to get this release out soon so I can focus on ECDMP and JOSM for the next few weeks. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58)*

**Comment by alyec** [comment]
Reviewed 1 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/58)*

**Pull request merged**
