### PR TITLE
Fix autodoc

### LINKED ISSUE #80: Travis autodoc build failure
Sphinx build failed when building document `index`.

Log: https://travis-ci.org/fgpv-vpgf/rcs/builds/344879164

### PR DESCRIPTION
**Pull request by barryytm**
Closes #80 

Update Sphinx to 1.6.6 to fix the build

Tested build: http://fgpv-vpgf.github.io/rcs/doctest/

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/81)

### CODE REVIEW

**Comment by alyec** [comment]
Docutils is now at 0.14 and ahccd is able to build without downgrading.  Can you look at updating either docutils to 0.14 or sphinx itself?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/81#-:-L6MrVm_Njo36L9ETosq:b-7417av)*

**Comment by barryytm** [comment]
Update Sphinx to 1.6.6 worked.  Tested build: http://fgpv-vpgf.github.io/rcs/doctest/

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/81#-:-L6N2kNpxezUbHkzak3a:bnfp4nl)*

**Comment by james-rae** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/81)*

**Pull request merged**
