### PR TITLE
Updates to test page, v2 service contract and other docs, final push for 2.0.0 final release

### PR DESCRIPTION
**Pull request by dan-bowerman**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/42)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42)*

**Comment by alyec** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[docs/admin/deployment.rst, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHH6cKEK8fX_KXz8ss:-KJHH6cKEK8fX_KXz8st:-534218483) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/admin/deployment.rst#L1)):*
> ```reStructuredText
> Deployment
> ```

There are a few new config options to be set, we should probably add those in a 2.0 section.

---

*[docs/service/contract.rst, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHGsM83VK6WqJ06R1G:-KJHGsM83VK6WqJ06R1H:-168752872) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L1)):*
> ```reStructuredText
> .. _contract:
> ```

General comment: can we change all `smallkey` references to `key` which should help make it clear that there is no limit besides URL length?

---

*[docs/service/contract.rst, line 6 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHBz9MUykVbm1RVyWI:-KJHBz9MUykVbm1RVyWJ:-159507608) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L6)):*
> ```reStructuredText
> ====================
> 
> This release of RCS publishes endpoints at ``/v2``.  The
> ```

We still have `/v1` endpoints for some operations.  I think we should try to include both on this page: https://github.com/fgpv-vpgf/rcs/blob/master/services/v1.py#L61

---

*[docs/service/contract.rst, line 100 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHGWMj4qmJxYSV42le:-KJHGWMj4qmJxYSV42lf:-2025336784) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L100)):*
> ```reStructuredText
>     {
>         "service_url": (str: URL to ESRI REST Feature Layer Endpoint),
>         "service_type": (str: Type of Esri Feature service),
> ```

basic records do not have a type specified.  It is left to the RCS to interrogate the service and make a best effort classification.  You might have gotten this field confused with `service_name` which is a property that can be optionally set.

---

*[docs/service/contract.rst, line 185 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHGJdOUPR3q2XNHFRv:-KJHGJdOUPR3q2XNHFRw:-1399661976) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L185)):*
> ```reStructuredText
>         "service_url": (str: URL to WMS Service),
>         "service_name": (str: Name of the service endpoint, used for display),
>         "service_type": (str: Service type of the endpoint, either ogcWms or ogcWmts),
> ```

We probably shouldn't advertise ogcWmts in the docs yet.  It's in place to make future RCS upgrades easier but I don't think the viewer can process it yet.

---

*[docs/service/contract.rst, line 188 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHFQetTTVeIQsTqc4N:-KJHFQetTTVeIQsTqc4O:-1939954833) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L188)):*
> ```reStructuredText
>         "scrape_only": (str array: Indicates which layer entries should be scraped,
>         all layers should be identified by their Name element.),
>         "recursive": (bool: Indicats if children should be scraped and made available
> ```

typo `Indicates`

---

*[docs/service/contract.rst, line 191 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHG8J5t9_UTQvZqPSS:-KJHG8J5t9_UTQvZqPST:-271241466) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L191)):*
> ```reStructuredText
>         as individual layers to the viewer),
>         "legend_format": (str: MIME type)",
>         "feature_info_type": (str: MIME type),
> ```

We now limit this to only 4 MIME types: "text/html;fgpv=summary", "text/html", "text/plain", "application/json"

---

*[docs/service/contract.rst, line 212 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHEvdOeNa7sl-hx2ha:-KJHEvdOeNa7sl-hx2hb:-1132082034) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L212)):*
> ```reStructuredText
> 
>     {
>         "service_url": (str: URL to WMS Service),]
> ```

extra `]`

---

*[docs/service/contract.rst, line 216 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHF2fk7T-IYhWZZpIX:-KJHF2fk7T-IYhWZZpIY:92545122) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L216)):*
> ```reStructuredText
>         "service_type": (str: Service type of the endpoint, either esriMapServer
>         or esriFeatureServer),
>         "scrape_only": (str array: Indicates which layer entries should be scraped,
> ```

I think this should be int array of layer indexes in the ESRI service.

---

*[docs/service/contract.rst, line 218 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHF86NPOWiwYZQnuS0:-KJHF86NPOWiwYZQnuS1:361547599) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L218)):*
> ```reStructuredText
>         "scrape_only": (str array: Indicates which layer entries should be scraped,
>         all layers should be identified by their Name element.),
>         "recursive": (bool: Indicats if children should be scraped and made available
> ```

typo `indicates`

---

*[docs/service/contract.rst, line 267 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHEKfko89ZIfnvt4x8:-KJHEKfko89ZIfnvt4x9:435321573) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L267)):*
> ```reStructuredText
> - Already upgraded
> 
> POST ``/v2/refresh/all``
> ```

The `all` is part of the arguments: https://github.com/fgpv-vpgf/rcs/blob/master/services/registration.py#L178 an age in days can also be specified.  It will upgrade records, but it can also update scraped data if necessary.

---

*[docs/service/quickref.rst, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHDlRxdey2Fi0Oja1O:-KJHDlRxdey2Fi0Oja1P:-1846152110) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/quickref.rst#L4)):*
> ```reStructuredText
> =======================
> 
> RCS currently exposes 6 REST endpoints.
> ```

These are out of date for v2.

---

*[docs/service/signing.rst, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHDtYOCCwki77iNrbk:-KJHDtYOCCwki77iNrbl:758808489) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/signing.rst#L56)):*
> ```reStructuredText
> #.  GeoCat computes the message string by concatenating the fragments specified in the `Protocol`_ section ::
> 
>         REQUEST_PATH = /v2/register/23ax5t
> ```

If you change /v1 to /v2 all the hashes change.  Either leave the /v1 example or update the Authorization header to be correct (this let's people use the example to see if they've implemented the hash correctly).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42)*

**Comment by james-rae** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42)*

**Comment by dan-bowerman** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[docs/admin/deployment.rst, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHH6cKEK8fX_KXz8ss:-KJLnfAgE9WgDc8xRZGi:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/admin/deployment.rst#L1)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> There are a few new config options to be set, we should probably add those in a 2.0 section.
</details>
Done.

---

*[docs/service/contract.rst, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHGsM83VK6WqJ06R1G:-KJLnfuVxwQONWFckwCH:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L1)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> General comment: can we change all `smallkey` references to `key` which should help make it clear that there is no limit besides URL length?
</details>
Done.

---

*[docs/service/contract.rst, line 6 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHBz9MUykVbm1RVyWI:-KJLngBMUqd0wv7oHQhD:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L6)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> We still have `/v1` endpoints for some operations.  I think we should try to include both on this page: https://github.com/fgpv-vpgf/rcs/blob/master/services/v1.py#L61
</details>
Done.

---

*[docs/service/contract.rst, line 100 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHGWMj4qmJxYSV42le:-KJLnghOkGILuzvKexiP:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L100)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> basic records do not have a type specified.  It is left to the RCS to interrogate the service and make a best effort classification.  You might have gotten this field confused with `service_name` which is a property that can be optionally set.
</details>
Done.

---

*[docs/service/contract.rst, line 185 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHGJdOUPR3q2XNHFRv:-KJLnh1RCZEmXvo-Zs2e:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L185)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> We probably shouldn't advertise ogcWmts in the docs yet.  It's in place to make future RCS upgrades easier but I don't think the viewer can process it yet.
</details>
Done.

---

*[docs/service/contract.rst, line 188 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHFQetTTVeIQsTqc4N:-KJLnnD8I9S4SI2ZTALD:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L188)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo `Indicates`
</details>
Done.

---

*[docs/service/contract.rst, line 191 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHG8J5t9_UTQvZqPSS:-KJLnhSiZOqEFUNfcKjP:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L191)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> We now limit this to only 4 MIME types: "text/html;fgpv=summary", "text/html", "text/plain", "application/json"
</details>
Done.

---

*[docs/service/contract.rst, line 212 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHEvdOeNa7sl-hx2ha:-KJLni5lugKChW1UgjR1:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L212)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> extra `]`
</details>
Done.

---

*[docs/service/contract.rst, line 216 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHF2fk7T-IYhWZZpIX:-KJLniO02MpZqR8mVyGm:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L216)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I think this should be int array of layer indexes in the ESRI service.
</details>
Done.

---

*[docs/service/contract.rst, line 218 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHF86NPOWiwYZQnuS0:-KJLnie3yQMGsgkf6pCn:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L218)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> typo `indicates`
</details>
Done.

---

*[docs/service/contract.rst, line 267 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHEKfko89ZIfnvt4x8:-KJLnj4f9giGIJEKKxOP:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/contract.rst#L267)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> The `all` is part of the arguments: https://github.com/fgpv-vpgf/rcs/blob/master/services/registration.py#L178 an age in days can also be specified.  It will upgrade records, but it can also update scraped data if necessary.
</details>
Done.

---

*[docs/service/quickref.rst, line 4 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHDlRxdey2Fi0Oja1O:-KJLnnxU67qFcB5N4mV6:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/quickref.rst#L4)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> These are out of date for v2.
</details>
Done.

---

*[docs/service/signing.rst, line 56 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJHDtYOCCwki77iNrbk:-KJLnocqmxWw-BXHcX_p:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/76d3ebd3ece7064553fc7b8de9d78432802765ea/docs/service/signing.rst#L56)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> If you change /v1 to /v2 all the hashes change.  Either leave the /v1 example or update the Authorization header to be correct (this let's people use the example to see if they've implemented the hash correctly).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[docs/admin/configuration.rst, line 38 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJLo6o7eofxJSE6iwwQ:-KJLo6o7eofxJSE6iwwR:-985822281) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5c1672f93c17c9b411028761101e3b54582dd97c/docs/admin/configuration.rst#L38)):*
> ```reStructuredText
>     A proxy URL to be used when registering layers.  Should be in the form of ``http://[server]:[port]``.
> PROD
>     Not sure!
> ```

PROD adds extra checks for production systems to make sure that test keys like `jstest` and `ecdmpdev` are not used for registration and ensures that `DEBUG_ENDPOINTS` and `SIG_CHECK` are set correctly (`false` and `true` respectively).

Please add DEBUG_ENDPOINTS as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42)*

**Comment by dan-bowerman** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/admin/configuration.rst, line 38 \[r2\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42#-KJLo6o7eofxJSE6iwwQ:-KJLrQYOjdtlwJqc6IlY:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/5c1672f93c17c9b411028761101e3b54582dd97c/docs/admin/configuration.rst#L38)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> PROD adds extra checks for production systems to make sure that test keys like `jstest` and `ecdmpdev` are not used for registration and ensures that `DEBUG_ENDPOINTS` and `SIG_CHECK` are set correctly (`false` and `true` respectively).
> 
> Please add DEBUG_ENDPOINTS as well.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/42)*

**Pull request merged**
