### PR TITLE
fix(registration): fix display field not being stored in layer registration

### LINKED ISSUE #48: Output nameField in layer configuration fragments
Make RCS output a nameField value in the JSON configuration fragment for layers if specified at registration time.

JSON schema has been updated in the following commit: https://github.com/james-rae/fgpv-vpgf/blob/289200820139ac18824c344de9bcb6db5a7dfd73/src/schema.json#L522

### PR DESCRIPTION
**Pull request by dan-bowerman**
display_field exists within the RCS 2.0.0 schema, but is not being set. This patch resolves this and stores the display_field as nameField within the CouchDB storage.

Closes #48

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/50)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50)*

**Comment by spencerwahl** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50)*

**Comment by alyec** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[docs/service/contract.rst, line 138 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50#-KMiOcwf6y89kWydZlZL:-KMiOcwf6y89kWydZlZM:887479457) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/47edc5b7f0f9993c68c214907e66e22f8c4932e9/docs/service/contract.rst#L138)):*
> ```reStructuredText
>         leaving the viewer to apply its own logic.),
>         "tolerance": (int: Tolerance, in pixels, of feature queries),
>         "recursive": (bool: Indicates if children should be scraped and made available
> ```

In the schema `service_type: "esriFeature"` will not be compatible with recursive.  Should this be on `esriMapServer`?

---

*[services/regparse/esri.py, line 239 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50#-KMiPAiAM5OzScAjlmSY:-KMiPAiBuq9b4YxWMs6R:915384200) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/47edc5b7f0f9993c68c214907e66e22f8c4932e9/services/regparse/esri.py#L239)):*
> ```Python
>         sublayer_json = []
>         if 'type' not in service_json:
>             for x in service_json['layers']:
> ```

Slightly cleaner with list comprehensions: `sublayer_json = [x for x in service_json['layers'] if x['parentLayerId'] == -1]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50#-:-KMihgx0vfDKkqjkrJrI:1417088721)*

**Comment by james-rae** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50)*

**Comment by alyec** [comment]
Sorry to add more work, can you also update the version in the docs config: https://github.com/fgpv-vpgf/rcs/blob/master/docs/conf.py#L61

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50#-:-KMinjWzR0RDPsBdbTx3:835948360)*

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50)*

**Comment by james-rae** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50)*

**Comment by dan-bowerman** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[services/regparse/esri.py, line 239 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50#-KMiPAiAM5OzScAjlmSY:-KMixOxMYAEHZ58Z8rR1:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/47edc5b7f0f9993c68c214907e66e22f8c4932e9/services/regparse/esri.py#L239)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Slightly cleaner with list comprehensions: `sublayer_json = [x for x in service_json['layers'] if x['parentLayerId'] == -1]`
</details>
Done.

---

*[docs/service/contract.rst, line 138 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50#-KMiOcwf6y89kWydZlZL:-KMixPyktXJsSMZYOOW1:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/47edc5b7f0f9993c68c214907e66e22f8c4932e9/docs/service/contract.rst#L138)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> In the schema `service_type: "esriFeature"` will not be compatible with recursive.  Should this be on `esriMapServer`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/50)*

**Pull request merged**
