### PR TITLE
Debug

### LINKED ISSUE #10: Add Debug Mode
- [ ] add `/log` and `/accesslog` endpoints to allow access to log files; require DEBUG=True for the end points to be active
- [ ] append a warning header to all traffic when RCS is in debug mode
- [ ] see if there is an easy way to prevent the default QA keys from being accidentally registered on the production database

### PR DESCRIPTION
**Pull request by alyec**
Should close #10 when merged.

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/23)

### CODE REVIEW

**Comment by spencerwahl** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/23)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/23)*

**Comment by dan-bowerman** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/23)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/23)*

**Pull request merged**
