### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by alyec**
[Review on Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/17)

### CODE REVIEW

**Comment by alyec** [comment]
Don't merge this until @ec-dev finishes schema changes for https://github.com/fgpv-vpgf/fgpv-vpgf/pull/377

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/17#-:-KCHVkBuWVjMnroJPRbL:-1491849730)*

**Comment by alyec** [comment]
Should be safe to merge now (still needs integration testing for metadata).

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/17#-:-KCM80bdlgYPbjLhHLab:1383897777)*

**Comment by spencerwahl** [comment]
Reviewed 1 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/17)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/17)*

**Pull request merged**
