### PR TITLE
Added support for recursive scraping of Esri and OGC services

### PR DESCRIPTION
**Pull request by dan-bowerman**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/46)

### CODE REVIEW

**Comment by james-rae** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46)*

**Comment by alyec** [comment]
Can you update the commit message to use the following guidelines: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#commit-message-format (for the scopes any of the top level python packages or modules work).

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[services/v2.py, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMzxiKy3-a4IczM7AQ:-KLMzxiKy3-a4IczM7AR:1933032935) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/v2.py#L1)):*
> ```Python
> from registration import Register, Refresh, Update
> ```

This adds update, but I don't see any changes in registration.py .  Was this an extra file in the commit?

---

*[services/regparse/esri.py, line 233 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMwTA7JA5Lti-4a3Zc:-KLMwTA7JA5Lti-4a3Zd:1142181160) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/regparse/esri.py#L233)):*
> ```Python
>         result['layerEntries'] = [{'index': index} for index in req['scrape_only']]
>     elif 'recursive' in req:
>         query_service = urllib2.Request(req['service_url'] + "?f=pjson")
> ```

It's generally better to use `requests` instead of urllib.  This will not work with the feature service proxies and there's a bunch of boilerplate code that can be avoided.  See https://github.com/fgpv-vpgf/rcs/blob/master/services/regparse/esri.py#L190 for an example.

---

*[services/regparse/esri.py, line 238 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMyG9vz61FlHKRKYi3:-KLMyG9vz61FlHKRKYi4:-969244296) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/regparse/esri.py#L238)):*
> ```Python
>         service_json = json.loads(f.read())
>         if service_json['type'] == 'Group Layer':
>             print req['service_url'][:-1]
> ```

Is the `[:-1]` to remove the last digit from the URL?  If so this will only work for single digits and it will fail if someone passes a URL ending with `/MapServer`

---

*[services/regparse/esri.py, line 242 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMwtQxBAJSc3Vggpkf:-KLMwtQyQ_gGFmBMb6iB:262135018) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/regparse/esri.py#L242)):*
> ```Python
>             result['url'] = req['service_url'][:-1]
>         sublayer_json = service_json['subLayers']
>         sub_layers = []
> ```

I think `result['layerEntries'] = [{'index': sl['id'] for sl in sublayer_json]` will work, I don't think there's a need to copy everything into `sub_layers` first.

---

*[services/regparse/ogc.py, line 73 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMzJi9JRM6ROhEgnfV:-KLMzJi9JRM6ROhEgnfW:-211424728) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/regparse/ogc.py#L73)):*
> ```Python
>     elif 'recursive' in req:
>         url_str = req['service_url'] + '?SERVICE=WMS&REQUEST=GetCapabilities'
>         xml_str = urllib.urlopen(url_str).read()
> ```

Use `requests` here as well if possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-:-KLN0giDcNXj5xa-dWNO:-1769235060)*

**Comment by dan-bowerman** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[services/v2.py, line 1 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMzxiKy3-a4IczM7AQ:-KLN5DpCmcjMfspWvWKT:-1025215359) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/v2.py#L1)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> This adds update, but I don't see any changes in registration.py .  Was this an extra file in the commit?
</details>
Yes, not much else has been done with update thus far.

---

*[services/regparse/esri.py, line 233 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMwTA7JA5Lti-4a3Zc:-KLNQisViyXdftHV3gcu:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/regparse/esri.py#L233)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> It's generally better to use `requests` instead of urllib.  This will not work with the feature service proxies and there's a bunch of boilerplate code that can be avoided.  See https://github.com/fgpv-vpgf/rcs/blob/master/services/regparse/esri.py#L190 for an example.
</details>
Done.

---

*[services/regparse/esri.py, line 238 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMyG9vz61FlHKRKYi3:-KLNO0lUwx5r-oCIJ5Ey:1065186326) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/regparse/esri.py#L238)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Is the `[:-1]` to remove the last digit from the URL?  If so this will only work for single digits and it will fail if someone passes a URL ending with `/MapServer`
</details>
Yes, but the code is only doing this on Group Layers, which in my experience always end in an integer. You do raise a point that this will be ineffective on double digit layers though, I've modified the way this is handled (`.rstrip('1234567890')`)

---

*[services/regparse/esri.py, line 242 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMwtQxBAJSc3Vggpkf:-KLNQdjOlCQ72fHSg1bw:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/regparse/esri.py#L242)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> I think `result['layerEntries'] = [{'index': sl['id'] for sl in sublayer_json]` will work, I don't think there's a need to copy everything into `sub_layers` first.
</details>
Done.

---

*[services/regparse/ogc.py, line 73 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMzJi9JRM6ROhEgnfV:-KLNNiM1TvKy-xf4jDbu:-890564855) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/regparse/ogc.py#L73)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> Use `requests` here as well if possible.
</details>
Requests seems to work only with JSON?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46)*

**Comment by alyec** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[services/regparse/ogc.py, line 73 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMzJi9JRM6ROhEgnfV:-KLOsdjGAze-aa32G7K3:1702995751) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/regparse/ogc.py#L73)):*
<details><summary><i>Previously, dan-bowerman (Dan Bowerman) wrote…</i></summary>
> Requests seems to work only with JSON?
</details>
`requests.get(wms_url).content` should work, I haven't used it in some time but it's definitely a general purpose library

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46)*

**Comment by dan-bowerman** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[services/regparse/ogc.py, line 73 \[r1\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KLMzJi9JRM6ROhEgnfV:-KLQja1UK_EymlmB6bsZ:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/23a5273ad0eaffca3df1c2dcc3cede33503e8804/services/regparse/ogc.py#L73)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> `requests.get(wms_url).content` should work, I haven't used it in some time but it's definitely a general purpose library
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46)*

**Comment by alyec** [comment]
Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46)*

**Comment by alyec** [comment]
Reviewed 3 of 4 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[run.py, line 66 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KM9qDVUgUBA9CUY-Zeq:-KM9qDVVTrFAmB-tOmlQ:-770909333) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/ba87df2c36c2ff0480d823666f9ad625b416c259/run.py#L66)):*
> ```Python
>     flask.g.get_validator = lambda: jsonschema.validators.Draft4Validator(json.load(open(schema_path)))
>     flask.g.proxies = {'http': app.config['HTTP_PROXY'], 'https': app.config['HTTP_PROXY']}
>     with open("setup.py") as f:
> ```

This will trigger on every request.  I think it would make more sense to move this inside the endpoint code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46)*

**Comment by dan-bowerman** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[run.py, line 66 \[r3\]](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-KM9qDVUgUBA9CUY-Zeq:-KMA1lJodpuT3UApNmpu:-499146009) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/ba87df2c36c2ff0480d823666f9ad625b416c259/run.py#L66)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> This will trigger on every request.  I think it would make more sense to move this inside the endpoint code.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/46#-:-KMA28Amuok3bV_k_JQB:1417088721)*

**Pull request merged**
