### PR TITLE
refactor(update): Refactored v2 Update endpoint

### LINKED ISSUE #59: Add a helper for cleaner v2 Update endpoint handling
From Aly: https://reviewable.io/reviews/fgpv-vpgf/rcs/58#-KTLU8VUScoSj82YORcf

```
request_seg = dbdata['request'][x]
payload_seg = payload[x]

def replace_if_set(params):
  for p in params:
    request_segment[p] = payload_seg[p]

replace_if_set('service_url service_name metadata'.split())
if payload_seg['service_type'] in ['esriFeature', 'esriImage', 'esriTile']:
  replace_if_set(['display_field'])
elif payload_seg['service_type'] == 'esriMapServer':
  replace_if_set(['scrape_only', 'recursive'])
elif payload_seg['service_type'] == 'ogcWms':
  replace_if_set(['scrape_only', 'recursive', 'legend_format', 'feature_info_format'])
```

### PR DESCRIPTION
**Pull request by dan-bowerman**
RCS v2 now supports the ability to update specific fields in a previous registration, without re-registering wholesale. WMS registrations will also store whether a layer is queryable or not. The refactor also resolves an issue where feature_info_format in WMS layers was not being set.

Closes #59, #60

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/rcs/62)

### CODE REVIEW

**Comment by alyec** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[setup.py, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/62#-KWcUmfWsq_mTZY5UAhZ:-KWcUmfWsq_mTZY5UAh_:b7rvxiq) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/aecd361c923f7c3f7be2c1cf6e0d14888f5732a2/setup.py#L10)):*
> ```Python
>     name="rcs",
>     description="RAMP Configuration Service",
>     version="2.2.1",
> ```

When the package version updates the docs config needs to be updated as well: https://github.com/fgpv-vpgf/rcs/blob/develop/docs/conf.py#L61

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/62)*

**Comment by alyec** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/62#-:-KWco6i6JfEuEy7h_tiV:bnfp4nl)*

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/62)*

**Comment by dan-bowerman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[setup.py, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/62#-KWcUmfWsq_mTZY5UAhZ:-KWcoVF2LorgwBQLCJPn:b-896fix) ([raw file](https://github.com/fgpv-vpgf/rcs/blob/aecd361c923f7c3f7be2c1cf6e0d14888f5732a2/setup.py#L10)):*
<details><summary><i>Previously, alyec (Aly Merchant) wrote…</i></summary>
> When the package version updates the docs config needs to be updated as well: https://github.com/fgpv-vpgf/rcs/blob/develop/docs/conf.py#L61
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/rcs/62)*

**Pull request merged**
